### ISSUE TITLE
Getting a weird crash with some file content

### ISSUE THREAD

**Issue by mxaddict** [coreyja/devicon-lookup#898]
```
rg --column --line-number --no-heading --color=always --smart-case -g '!.git' -- '' src/univalue/test/fail40.json | RUST_BACKTRACE=full devicon-lookup
```

```
thread 'main' panicked at 'Failed to read line from stdin: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', /home/mxaddict/.cargo/registry/src/github.com-1ecc6299db9ec823/devicon-lookup-0.8.1/src/main.rs:47:44
stack backtrace:
   0:     0x55c982fe2883 - std::backtrace_rs::backtrace::libunwind::trace::he0156af2558114c2
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c982fe2883 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e2672bcf5105eb5
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c982fe2883 - std::sys_common::backtrace::_print_fmt::haa919a14d8d859ec
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55c982fe2883 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf15e8f9e6884dd5f
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55c982ffa36c - core::fmt::write::he42254d9e3c27115
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/fmt/mod.rs:1202:17
   5:     0x55c982fcef55 - std::io::Write::write_fmt::hfb37e0ab3a125c66
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/io/mod.rs:1679:15
   6:     0x55c982fd1074 - std::sys_common::backtrace::_print::h8078bdb0e2e92b53
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55c982fd1074 - std::sys_common::backtrace::print::h09fd65486fb9c4f7
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55c982fd1074 - std::panicking::default_hook::{{closure}}::hb89b98c578903f40
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:295:22
   9:     0x55c982fd0cb4 - std::panicking::default_hook::h27aa44be03b01ac8
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:314:9
  10:     0x55c982fd1653 - std::panicking::rust_panic_with_hook::he7013d2ea706cde0
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:698:17
  11:     0x55c982fe2e57 - std::panicking::begin_panic_handler::{{closure}}::hd66fe345adc7bed2
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:588:13
  12:     0x55c982fe29c4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha2b47ffe9f27aed9
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55c982fd1342 - rust_begin_unwind
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:584:5
  14:     0x55c982f16d13 - core::panicking::panic_fmt::hbfca70bd08ba6212
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/panicking.rs:142:14
  15:     0x55c982f16df3 - core::result::unwrap_failed::h24a3d44a1b5e0507
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/result.rs:1785:5
  16:     0x55c982f1e614 - devicon_lookup::main::h7231f21ade7b283d
  17:     0x55c982f1ec33 - std::sys_common::backtrace::__rust_begin_short_backtrace::hab84cb5ed01dc8e4
  18:     0x55c982f17a89 - std::rt::lang_start::{{closure}}::h368d68707a2dcbe3
  19:     0x55c982fce4c8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h62af992155415807
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/ops/function.rs:283:13
  20:     0x55c982fce4c8 - std::panicking::try::do_call::hcfafbbba7d4f6a6c
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:492:40
  21:     0x55c982fce4c8 - std::panicking::try::h7ee1bfcad42abe9b
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:456:19
  22:     0x55c982fce4c8 - std::panic::catch_unwind::h009aa132eb8dd7d2
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panic.rs:137:14
  23:     0x55c982fce4c8 - std::rt::lang_start_internal::{{closure}}::h93ae259af980c7d0
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/rt.rs:148:48
  24:     0x55c982fce4c8 - std::panicking::try::do_call::ha0627c997265a210
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:492:40
  25:     0x55c982fce4c8 - std::panicking::try::h64a0afc1377cc785
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:456:19
  26:     0x55c982fce4c8 - std::panic::catch_unwind::h1c61ea510b397b89
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panic.rs:137:14
  27:     0x55c982fce4c8 - std::rt::lang_start_internal::ha75927e1903320fe
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/rt.rs:148:20
  28:     0x55c982f1e8c8 - main
  29:     0x7f9d2610bd90 - <unknown>
  30:     0x7f9d2610be40 - __libc_start_main
  31:     0x55c982f16ea5 - _start
  32:                0x0 - <unknown>
  ```

contents of src/univalue/test/fail40.json:
```
["¡"]
```

**Comment by coreyja** [comment]
Hey thanks for the report @mxaddict!

`devicon-lookup` definitely doesn't have good (or any) support for non UTF-8 input

Would a reasonable solution for your use case be to just pass that line through un-edited?

**Comment by coreyja** [comment]
Sorry @mxaddict Sorry @mxaddict let me explain a bit more!

devicon-lookup (because it uses the Rust stdlib) can only handle `String`s that are [UTF-8 encoded](https://en.wikipedia.org/wiki/UTF-8). 

I'm pretty sure that some of the characters in that test file `src/univalue/test/fail40.json` are not valid UTF-8 [which is one reason they render as the unicode `?` in github I believe]

I believe `rg` is doing the 'correct' thing and passing these characters over stdout, to `devicon-lookup`, which immediately tries to parse them as UTF-8 (and then blows up)

`devicon-lookup` works line by line, so I was wondering if a potential solution to this would be to NOT try actually parsing this line since it isn't valid UTF-8, and just pipe it through un-changed.
I think this should have the expected effect, this line just wouldn't get a devicon prepended.

But as I write that I don't think it will be quite as simple as that :thinking:
Because I belive we are using the `lines()` method here to loop over all the lines of the std input, and I think this assumes UTF-8 already so could be interesting to slot in 🤔 

But either way thanks for the report! Will have to think about the best way to handle this!

**Comment by mxaddict** [comment]
Maybe if instead of handling the line as UTF-8, why not do a lossy pass on the line?

This should allow you to bypass the UTF-8 error on rust stdlib, not sure how to do that though

So in the line that calls `stdin.lock().lines()` Is there a method that allows for a non String to be passed, like binary, then convert from that datatype with `String::from_utf8_lossy()`

**Comment by coreyja** [comment]
Hey @mxaddict!

Thanks again for this bug report!

I just pushed a new version `0.9.1` which should fix this issue. `devicon-lookup` now passes through any non-UTF8 lines it sees, so you should _not_ get crashes anymore!

You will still not see any icons on lines containing non-UT8 characters. If that isn't the behavior you wanted or expected, please feel free to open a new issue!

Thanks again for using `devicon-lookup`!

And quick personal plug! I did most of this fix on stream! If you want to check out the VOD I will post the link in this comment once I wrap up!
My twitch is at https://twitch.tv/coreyja

**Comment by mxaddict** [comment]
Nice.

Cheers,
Barry Deeney
